version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: chess_opening_master_mongodb
    environment:
      - MONGO_INITDB_DATABASE=chess_opening_master
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
